server.port: 8080

spring:
  application:
    name: monitoring
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.mongodb.driver.cluster: NONE

#algashop:
#  data-load:
#    enabled: false
#    auto-delete: false
#    sources:
#      - location: db/testdata/categories.json
#        collection: categories
#      - location: db/testdata/products.json
#        collection: products

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: always
#      group:
#        readiness:
#          include:
#            - mongo
#            - readinessState
#      status:
#        order: "DOWN, OUT_OF_SERVICE, UNKNOWN, DEGRADED, UP"
#  info:
#    env.enabled: true
#  health:
#    redis:
#      enabled: false

info:
  app.name: Monitoring API